name: Build and Push Docker Images


on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Docker Hub using token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Frontend image
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-qrcode-frontend:latest ./front-end-nextjs
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-qrcode-frontend:latest

      # Build and push API image
      - name: Build and Push API
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-qrcode-api:latest ./api
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-qrcode-api:latest
